name: pointcept
channels:
  - pytorch
  - nvidia/label/cuda-12.1.1
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.1
  - gcc=13.2
  - gxx=13.2
  - ninja
  - google-sparsehash
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - yapf=0.31.0
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
  - pip:
    - SharedArray
    - torch-cluster -f https://data.pyg.org/whl/torch-2.5.0+cu121.html
    - torch-scatter -f https://data.pyg.org/whl/torch-2.5.0+cu121.html
    - torch-sparse -f https://data.pyg.org/whl/torch-2.5.0+cu121.html
    - torch_geometric
    - spconv-cu121
    - git+https://github.com/octree-nn/ocnn-pytorch.git
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/Dao-AILab/flash-attention.git
    - ./libs/pointops
    - ./libs/pointgroup_ops
